apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
  labels:
    app: fiapml
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fiapml
  template:
    metadata:
      labels:
        app: fiapml
    spec:
      containers:
        - name: fiapml
          image: "tonanuvem/ml-perfil-aluno-custom-model"
          ports:
            - name: http
              containerPort: 80
kind: Service
apiVersion: v1
metadata:
  name: ml-service
spec:
  selector:
    app: fiapml
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 32000
  type: NodePort
